spring:
  datasource:
    url: jdbc:h2:mem:testdb;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: test
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true